YERLER = [
	{
		"id": 1,
		"isim": "Taşköprü",
		"sehir": "Adana",
		"kategori": "Tarihi Yapılar",
		"lat": 37.0000,
		"lon": 35.3213,
		"kisa": "Roma döneminden kalma tarihi taş köprü.",
		"uzun": "Taşköprü, Adana'nın görkemli tarih mirasının sembolü olarak Seyhan Nehri üzerinde yükselen eşsiz bir yapıdır. Roma döneminde inşa edilmiş olan bu köprü, 14 kemerli mimarisiyle 310 metre uzunluğunda ve 4 metre genişliğindedir. Adana'nın simgelerinden biri olan Taşköprü, binlerce yıldır şehrini ticari ve kültürel açıdan birleştirmiştir. Günümüzde hala işlevsel olarak kullanılan köprü, yaya trafiğine tamamen açık olup pek çok turisti cezbetmektedir. Tarihi dönemlerde ordular bu köprüden geçerken, bugün ise binlerce ziyaretçi tarihe yolculuk yapmak amacıyla buraya gelmektedir.",
		"resim": "images/adana-taskopru.svg",
		"images": ["images/adana-taskopru.svg"]
	},
	{
		"id": 2,
		"isim": "Sabancı Merkez Camii",
		"sehir": "Adana",
		"kategori": "Dini/Dindar",
		"lat": 37.0014,
		"lon": 35.3289,
		"kisa": "Türkiye'nin en büyük camilerinden biri.",
		"uzun": "Sabancı Merkez Camii, Adana'nın modern mimarinin ve İslam sanatının eşsiz bir örneğidir. 1998 yılında tamamlanan bu eser, altı minareli görkemli mimarisiyle Türkiye'nin en büyük camilerinden biridir. 28.500 kişilik muazzam kapasitesiyle ibadet ve kültürel etkinliklere ev sahipliği yapmaktadır. Caminin iç mekanı zarif tezyinatı, geniş avlu ve konforlu sünnet kapısıyla ziyaretçileri büyülemektedir. Sabancı ailesinin kültür ve sanata yönelik sorumluluk duygusunun bir sembolü olan bu cami, mimar Vedat Dalokay'ın eserinin en iyi örneklerinden biridir. Adana'nın sembolik yapılarından olan bu cami, hem dini hem de sanat tarihi açısından oldukça önem taşımaktadır.",
		"resim": "images/adana-sabanci.svg",
		"images": ["images/adana-sabanci.svg"]
	},
	{
		"id": 3,
		"isim": "Adana Arkeoloji Müzesi",
		"sehir": "Adana",
		"kategori": "Müzeler",
		"lat": 37.0058,
		"lon": 35.3250,
		"kisa": "Bölgenin zengin arkeolojik mirasını sergiler.",
		"uzun": "Adana Arkeoloji Müzesi, Çukurova bölgesinin binlerce yıllık zengin arkeolojik mirasını korumakta ve sergileyen en önemli kültür kurumlarından biridir. Hitit, Pers, Hellenistik, Roma ve Bizans dönemlerine ait eserler içeren müze, çok değerli buluntularla doldurulmuştur. Özellikle Portakal Bahçesi Mozaiği, antik sikke koleksiyonu ve Roma heykelleri müzenin en dikkat çeken eserleridir. Müzede sergilenen her eser, Çukurova'nın tarih içindeki önemini ve yoğun yerleşim hayatını gözler önüne sermektedir. Arkeoloji meraklıları için kaçırılmayacak bir destinasyon olan müze, 2022 yılında yeni binayla taşınmış ve modernize edilmiştir. Müze, Hitit imparatorluğundan Osmanlı dönemine kadar pek çok medeniyetin izlerini taşımaktadır.",
		"resim": "images/adana-muze.svg",
		"images": ["images/adana-muze.svg"]
	},
	{
		"id": 4,
		"isim": "Anavarza Antik Kenti",
		"sehir": "Adana",
		"kategori": "Arkeolojik Alanlar",
		"lat": 37.2500,
		"lon": 35.9000,
		"kisa": "Roma ve Bizans dönemine ait antik kent kalıntıları.",
		"uzun": "Anavarza, antik çağda önemli bir ticaret merkezi olup Roma ve Bizans dönemlerinin en görkemli şehirlerinden biri idi. Konya Derbent bölgesinde yer alan bu antik kent, tarihi ipek yolunun önemli bir noktasıydı. Kentte korunmuş halde kale, tiyatro, su kemerleri (aqueduct), triumphal kapı ve bazilikalar yer almaktadır. Özellikle çift katlı Roma tiyatrosu ve mozaikli yapıları arkeoloji tarihinde önemli yer tutmaktadır. Sütunlu caddeleri ve geniş agora alanı, şehrin tarihte ne kadar gelişmiş olduğunu göstermektedir. Sütunlu sokaklar, kamu binalarının kalıntıları ve mezar taşları antik dönemin yaşam tarzına ışık tutmaktadır. Anavarza, 8. yüzyılda Arap saldırıları sonucu terk edilmiş ve zamanla harap olmuştur.",
		"resim": "images/adana-anavarza.svg",
		"images": ["images/adana-anavarza.svg"]
	},
	{
		"id": 5,
		"isim": "Yılankale",
		"sehir": "Adana",
		"kategori": "Tarihi Yapılar",
		"lat": 36.8833,
		"lon": 35.8833,
		"kisa": "Orta çağ Ermeni kalesi.",
		"uzun": "Yılankale, Adana'nın Ceyhan ilçesinde Ceyhan Nehri kıyısında yüksek bir tepe üzerinde kurulmuş muhteşem bir Orta Çağ kalesidir. 12. yüzyılda Ermeni Kilikya Krallığı döneminde inşa edilen bu kale, stratejik konumu sayesinde Çukurova ovasını ve ticaret yollarını kontrol eden önemli bir savunma noktasıydı. Kalenin adının yılanlardan geldiğine dair rivayetler bulunmakla birlikte, bazı kaynaklara göre bölgede yılan bolluğundan dolayı bu ismi aldığı söylenmektedir. Kale, surları, gözetleme kuleleri, su sarnıçları ve iç kalesi ile dönemin savunma mimarisinin mükemmel bir örneğidir. Haçlı Seferleri döneminde stratejik öneme sahip olan kale, 13. yüzyılda Memlük akınlarına karşı direniş göstermiştir. Günümüzde turistik bir cazibe merkezi olan Yılankale'den Çukurova'nın eşsiz manzarası izlenebilmektedir.",
		"resim": "images/adana-yilankale.svg",
		"images": ["images/adana-yilankale.svg"]
	},
	{
		"id": 6,
		"isim": "Ramazanoğlu Konağı",
		"sehir": "Adana",
		"kategori": "Tarihi Yapılar",
		"lat": 37.0000,
		"lon": 35.3250,
		"kisa": "16. yüzyıl Osmanlı konağı.",
		"uzun": "Ramazanoğlu Konağı, 16. yüzyılda Ramazanoğulları Beyliği döneminde inşa edilmiş ve geleneksel Osmanlı konak mimarisinin en zarif örneklerinden biri olan muhteşem bir yapıdır. İki katlı taş konak, cumba ve ahşap işçiliği ile dönemin sanat anlayışını yansıtmaktadır. Konağın iç mekanında yer alan oyma tavanlar, el işlemeli taş süslemeler ve seramik çiniler Osmanlı sanatının inceliklerini gözler önüne sermektedir. 1979 yılında kapsamlı bir restorasyon geçiren konak, günümüzde etnografya müzesi olarak ziyarete açılmıştır. Müzede geleneksel Adana yaşamına ait eşyalar, kıyafetler, el sanatları ve günlük yaşam objelerinin sergilendiği bölümler bulunmaktadır. Konağın avlusu ve bahçesi de dönemin peyzaj anlayışını yansıtacak şekilde düzenlenmiştir. Ramazanoğlu Konağı, Adana'nın kültürel mirasının korunması açısından büyük önem taşımaktadır.",
		"resim": "images/adana-konak.svg",
		"images": ["images/adana-konak.svg"]
	},
	{
		"id": 7,
		"isim": "Misis Mozaik Müzesi",
		"sehir": "Adana",
		"kategori": "Müzeler",
		"lat": 37.0333,
		"lon": 35.6167,
		"kisa": "Roma dönemi mozaiklerini sergiler.",
		"uzun": "Misis Mozaik Müzesi, Adana'nın Yakapınar (eski adıyla Misis) beldesinde bulunan ve antik Misis kentinden çıkarılan Roma ve Bizans dönemine ait muhteşem mozaikleri korumak ve sergilemek amacıyla kurulmuş özel bir müzedir. 4. yüzyıla tarihlenen ve müzenin en değerli eseri olan 'Nuh'un Gemisi' mozaiği, dini sahneleri betimleyen nadir mozaiklerden biridir. Bu mozaik, Hristiyan sanatının erken dönem örnekleri arasında yer almakta ve uluslararası düzeyde tanınmaktadır. Müzede ayrıca mitolojik sahneler, geometrik desenler ve günlük yaşamı betimleyen mozaikler sergilenmektedir. Antik Misis kenti, Roma döneminde önemli bir ticaret merkezi olup İpek Yolu üzerinde bulunmaktaydı. Müzenin bulunduğu bölgede yapılan arkeolojik kazılar sonucunda ortaya çıkarılan mozaikler, dönemin zenginliğini ve sanatsal seviyesini göstermektedir. Misis Köprüsü ile birlikte ziyaret edilmesi gereken bu müze, bölgenin tarihi dokusunu anlamak için önemli bir duraktır.",
		"resim": "images/adana-misis.svg",
		"images": ["images/adana-misis.svg"]
	},
	{
		"id": 8,
		"isim": "Anıtkabir",
		"sehir": "Ankara",
		"kategori": "Tarihi Kalıntılar",
		"lat": 39.9259,
		"lon": 32.8381,
		"kisa": "Mustafa Kemal Atatürk'ün anıt mezarı.",
		"uzun": "Anıtkabir, Türkiye Cumhuriyeti'nin kurucusu Mustafa Kemal Atatürk'ün anıt mezarı olarak Ankara'nın Anıttepe semtinde görkemli bir şekilde yükselmektedir. 1944-1953 yılları arasında 9 yıl süren inşaat sürecinin ardından tamamlanan bu muhteşem yapı, modern Türk mimarisinin en önemli eserlerinden biridir. Mimar Emin Onat ve Orhan Arda tarafından tasarlanan Anıtkabir, 750.000 metrekarelik devasa bir alana yayılmaktadır. Aslan Yolu, Tören Meydanı, On Kule ve Mozole bölümlerinden oluşan kompleks, her ayrıntısında Türk tarihine ve Atatürk'ün mücadelesine atıflar içermektedir. Atatürk'ün naaşının bulunduğu Mozole, muazzam kubbesi ve zarif sütunlarıyla mimari bir başyapıttır. Anıtkabir Müzesi'nde Atatürk'ün özel eşyaları, kıyafetleri, silahları, madalyaları ve dünya liderlerinden aldığı hediyeler sergilenmektedir. Her yıl milyonlarca yerli ve yabancı ziyaretçi bu kutsal mekâna saygı duruşunda bulunmak için gelmektedir.",
		"resim": "images/istockphoto-471509753-612x612.jpg",
		"images": ["images/istockphoto-471509753-612x612.jpg"]
	},
	{
		"id": 71,
		"isim": "Hacı Bayram Camii",
		"sehir": "Ankara",
		"kategori": "Dini/Dindar",
		"lat": 39.9196,
		"lon": 32.8572,
		"kisa": "Osmanlı dönemi camii, Hacı Bayram-ı Veli'ye adanmış.",
		"uzun": "Hacı Bayram Camii, Ankara'nın Ulus semtinde yer alan ve 15. yüzyılın başlarında inşa edilmiş tarihi ve manevi değeri yüksek bir dini yapıdır. Ankara'nın en eski camilerinden biri olan bu muhteşem eser, Hacı Bayram-ı Veli'nin türbesi ile birlikte bir külliye oluşturmaktadır. Hacı Bayram-ı Veli, Anadolu tasavvuf geleneğinin en önemli şahsiyetlerinden biri olup, Bayrami tarikatının kurucusudur. Caminin mimari yapısı, klasik Osmanlı tarzının sadelik ve zarafetini yansıtmaktadır. Kesme taş duvarları, ahşap işlemeli minberi ve çinileri ile dikkat çeken cami, Augustus Tapınağı kalıntılarının hemen yanında bulunması nedeniyle tarih katmanlarının iç içe geçtiği nadir yerlerdendir. Her yıl binlerce ziyaretçi hem ibadethane olarak hem de Hacı Bayram-ı Veli'nin türbesini ziyaret etmek için bu camiye gelmektedir. Cami avlusunda tarihi çınar ağaçları ve çeşmeler bulunmakta olup, Ankara'nın tarihi dokusunun en önemli parçalarından birini oluşturmaktadır.",
		"resim": "images/hacibayram-1.svg",
		"images": ["images/hacibayram-1.svg"]
	},
	{
		"id": 72,
		"isim": "Roma Hamamı (A.Ankara)",
		"sehir": "Ankara",
		"kategori": "Arkeolojik Alanlar",
		"lat": 39.9240,
		"lon": 32.8620,
		"kisa": "Roma döneminden kalma hamam kalıntıları.",
		"uzun": "Roma Hamamı, Ankara'nın antik adı Ancyra'da M.S. 3. yüzyılda Roma İmparatoru Caracalla döneminde inşa edilmiş devasa bir sosyal yapının kalıntılarıdır. Ulus semtindeki Çankırı Caddesi üzerinde bulunan bu arkeolojik alan, Roma döneminin sosyal yaşam ve mimari mühendislik anlayışını yansıtan en önemli yapılardan biridir. Hamam, frigidarium (soğuk su bölümü), tepidarium (ılık su bölümü) ve caldarium (sıcak su bölümü) olmak üzere üç ana bölümden oluşmaktadır. Roma döneminde hamamlar sadece yıkanma yeri değil, aynı zamanda sosyalleşme, spor yapma ve siyasi tartışmaların yapıldığı önemli toplumsal merkezlerdi. Yapının altında yer alan hypocaust sistemi (yerden ısıtma sistemi), Roma mühendisliğinin ne kadar gelişmiş olduğunun bir kanıtıdır. Günümüzde kazı ve restorasyon çalışmaları devam eden Roma Hamamı, ziyaretçilere antik döneme ait mozaikler, mermer sütunlar ve mimari detaylar sunmaktadır.",
		"resim": "images/romahami-1.svg",
		"images": ["images/romahami-1.svg"]
	},
	{
		"id": 73,
		"isim": "Kocatepe Camii",
		"sehir": "Ankara",
		"kategori": "Dini/Dindar",
		"lat": 39.9208,
		"lon": 32.8541,
		"kisa": "Modern dönemin en büyük camilerinden biri.",
		"uzun": "Kocatepe Camii, Ankara'nın Kızılay semtinde yer alan ve 1967-1987 yılları arasında 20 yıl süren bir inşaat sürecinin ardından tamamlanan Türkiye'nin en büyük ve görkemli camilerinden biridir. Klasik Osmanlı mimarisi ile modern tekniklerin mükemmel bir sentezini yansıtan cami, mimar Vedat Dalokay tarafından tasarlanmıştır. Dört minareli yapısı, dev kubbesi ve 24.000 kişilik ibadet kapasitesiyle dikkat çekmektedir. Caminin iç mekanında yer alan Kütahya çinileri, altın varaklı hat yazıları, kristal avizeler ve mermer işçiliği Türk-İslam sanatının en güzel örneklerindendir. Ana kubbenin yüksekliği 37 metre, çapı ise 25 metredir. Caminin altında bulunan alışveriş merkezi, konferans salonları ve sosyal tesisler, dini işlevinin yanı sıra modern bir toplumsal yaşam merkezi özelliği de taşımaktadır. Ankara'nın panoramik manzarasına hakim konumu ile hem ibadet hem de mimari hayranlık için ziyaret edilen Kocatepe Camii, başkentin sembollerinden biri haline gelmiştir.",
		"resim": "images/kocatepe-1.svg",
		"images": ["images/kocatepe-1.svg"]
	},
	{
		"id": 74,
		"isim": "Anadolu Medeniyetleri Müzesi",
		"sehir": "Ankara",
		"kategori": "Müzeler",
		"lat": 39.9250,
		"lon": 32.8543,
		"kisa": "Zengin Anadolu tarihine ait eserler sergilenir.",
		"uzun": "Anadolu Medeniyetleri Müzesi, Ankara'nın Ulus semtinde tarihi Mahmut Paşa Bedesteni ve Kurşunlu Han binalarında yer alan, Anadolu topraklarının on binlerce yıllık medeniyetler hazinesini sergileyen dünyanın en prestijli arkeoloji müzelerinden biridir. 1921 yılında kurulan müze, Paleolitik Çağ'dan Osmanlı dönemine kadar uzanan kronolojik bir sergileme düzeni sunmaktadır. Hitit İmparatorluğu'nun güneş kursu sembolü, Urartu medeniyetinin bronz heykelleri, Frig Krallığı'nın ahşap eşyaları ve Neolitik Çatalhöyük yerleşiminden çıkan Ana Tanrıça figürleri müzenin en değerli eserleri arasındadır. 1997 yılında 'Avrupa'nın Yılın Müzesi' ödülüne layık görülen müze, dünya çapında arkeoloji meraklılarının ilgisini çekmektedir. Müzede ayrıca çivi yazısı tabletler, antik dönem takıları, seramikler ve günlük yaşam objelerinden oluşan zengin bir koleksiyon bulunmaktadır. Ziyaretçiler için rehberli turlar ve eğitim programları düzenli olarak organize edilmektedir.",
		"resim": "images/place-5.svg",
		"images": ["images/place-5.svg"]
	},
	{
		"id": 75,
		"isim": "Hamamönü",
		"sehir": "Ankara",
		"kategori": "Tarihi Semt",
		"lat": 39.9305,
		"lon": 32.8629,
		"kisa": "Restore edilmiş Osmanlı mahallesi ve el sanatları bölgesi.",
		"uzun": "Hamamönü, Ankara'nın Altındağ ilçesinde bulunan ve kapsamlı bir restorasyon projesiyle tarihi dokusuna kavuşturulmuş geleneksel Osmanlı mahallesidir. 19. yüzyılda inşa edilen ahşap ve taş konakları, dar taş döşeli sokakları ve geleneksel mimarisiyle ziyaretçileri zamanda yolculuğa çıkarmaktadır. Mahallenin adını aldığı tarihi Karacabey Hamamı, 15. yüzyılda inşa edilmiş olup, Osmanlı hamam mimarisinin güzel bir örneğidir. 2010-2014 yılları arasında gerçekleştirilen restorasyon çalışmalarıyla Hamamönü, Ankara'nın kültürel ve turistik merkezlerinden biri haline gelmiştir. Bölgede bakırcılık, çinicilik, halıcılık, hat sanatı ve ebru gibi geleneksel el sanatlarının atölyeleri faaliyet göstermektedir. Dar sokakları boyunca sıralanan tarihi konaklar, bugün butik kafeler, antika dükkanları, sanat galerileri ve müzeler olarak hizmet vermektedir. Hafta sonları sokak müzisyenleri, halk dansları gösterileri ve kültürel etkinliklerle canlanan Hamamönü, hem yerel halk hem de yerli ve yabancı turistler için cazip bir destinasyondur.",
		"resim": "images/place-6.svg",
		"images": ["images/place-6.svg"]
	},
	{
		"id": 76,
		"isim": "Etnografya Müzesi",
		"sehir": "Ankara",
		"kategori": "Müzeler",
		"lat": 39.9257,
		"lon": 32.8502,
		"kisa": "Türk etnografyasına ait eserler sergilenir.",
		"uzun": "Etnografya Müzesi, Ankara'nın Namazgah Tepesi'nde 1925 yılında Atatürk'ün direktifleriyle kurulan ve Türk kültürünün maddi ve manevi mirasını sergileyen önemli bir müzedir. Müze binası, klasik Selçuklu ve Osmanlı mimarisinin sentezini yansıtan neoklasik bir yapıdır. Koleksiyonlar arasında Selçuklu ve Osmanlı dönemlerine ait el yazması Kur'an-ı Kerimler, çini ve seramik eserler, ahşap işlemeli kapılar, minberler, geleneksel giysiler, takılar, silahlar, müzik aletleri, halılar, kilimler ve günlük yaşam eşyaları yer almaktadır. Anadolu'nun farklı bölgelerinden (Ege, Karadeniz, Doğu Anadolu, Güneydoğu Anadolu) getirilen etnografik malzemeler, kültürel çeşitliliği göstermektedir. Müzede ayrıca geleneksel Türk evi, düğün odası ve kahve köşesi gibi dönem oda düzenlemeleri bulunmaktadır. Bu odalar, ziyaretçilere Osmanlı ve Cumhuriyet dönemi yaşam tarzlarını deneyimleme fırsatı sunmaktadır. 1930'larda Atatürk'ün naaşı da Anıtkabir'in inşası tamamlanana kadar bu müzede muhafaza edilmiştir.",
		"resim": "images/place-7.svg",
		"images": ["images/place-7.svg"]
	},
	{
		"id": 77,
		"isim": "Atatürk Orman Çiftliği",
		"sehir": "Ankara",
		"kategori": "Doğa",
		"lat": 39.9243,
		"lon": 32.7986,
		"kisa": "Geniş park ve tarım alanları, seralar.",
		"uzun": "Atatürk Orman Çiftliği (AOÇ), Mustafa Kemal Atatürk tarafından 1925 yılında kurulan ve Ankara'nın batısında 10.000 hektarlık devasa bir alanda yayılan tarihi bir tarım işletmesi ve rekreasyon merkezidir. Atatürk'ün modern tarım tekniklerini Türkiye'de yaygınlaştırma ve çağdaş bir tarım modeli oluşturma vizyonuyla kurulan çiftlik, Cumhuriyet döneminin ilk büyük tarımsal projelerinden biridir. Çiftlikte süt ve bira fabrikaları, mandıra, bağlar, seraları, meyve bahçeleri, hayvancılık tesisleri ve ormanlık alanlar bulunmaktadır. AOÇ'nin meşhur ürünleri arasında dondurma, süt, peynir, tereyağı ve bira gibi yerel lezzetler yer almaktadır. Gençlik Parkı, Marmara Köşkü, Cumhurbaşkanlığı Köşkü ve göletler gibi tarihi yapılar çiftlik içinde ziyaret edilebilir. Her yıl milyonlarca Ankara'lı ve turist piknik yapmak, bisiklet sürmek, yürüyüş yapmak ve yeşil alanlarda vakit geçirmek için AOÇ'yi ziyaret etmektedir. Çiftlik, aynı zamanda tarım eğitimi ve araştırma faaliyetleri için de kullanılmaktadır.",
		"resim": "images/place-8.svg",
		"images": ["images/place-8.svg"]
	},
	{
		"id": 9,
		"isim": "Gençlik Parkı",
		"sehir": "Ankara",
		"kategori": "Parklar",
		"lat": 39.9261,
		"lon": 32.8590,
		"kisa": "Şehir merkezindeki büyük park ve gölet.",
		"uzun": "Gençlik Parkı, Ankara'nın Ulus ve Sıhhiye semtleri arasında yer alan, 1943 yılında dönemin Ankara Valisi Nevzat Tandoğan tarafından açılan ve 27 hektarlık alanıyla şehrin en büyük kent parklarından biridir. Eskiden bataklık olan bu alan, büyük bir dönüşüm projesiyle yeşil bir rekreasyon alanına dönüştürülmüştür. Parkın merkezinde büyük bir yapay gölet bulunmaktadır ve gölet üzerinde sandal turları yapılabilmektedir. 1950'li ve 1960'lı yıllarda Ankara'nın sosyal yaşamının kalbini oluşturan park, açılış yıllarında Türkiye'nin ilk luna park eğlence merkezi ve açık hava tiyatrosuyla dikkat çekmiştir. Parkta çeşitli heykeller, anıtlar, çocuk oyun alanları, spor sahaları, kafeler ve restoranlar bulunmaktadır. Yaz aylarında açık hava konserleri, tiyatro gösterileri ve kültürel etkinlikler düzenlenmektedir. Gençlik Parkı, aynı zamanda nostaljik atmosferi, tarihi lunaparkı ve döner köşkleriyle Ankara'nın kollektif hafızasında özel bir yere sahiptir. Aileler için piknik alanları ve gençler için buluşma noktası olan park, hala şehrin en sevilen yeşil alanlarından biridir.",
		"resim": "images/place-9.svg",
		"images": ["images/place-9.svg"]
	},
	{
		"id": 10,
		"isim": "Hacı Bayram Türbesi",
		"sehir": "Ankara",
		"kategori": "Tarihi Yapılar",
		"lat": 39.9193,
		"lon": 32.8570,
		"kisa": "Hacı Bayram-ı Veli'nin türbesi.",
		"uzun": "Hacı Bayram Türbesi, Anadolu tasavvuf geleneğinin büyük simalarından Hacı Bayram-ı Veli'nin (1352-1430) kabrinin bulunduğu ve Ankara'nın manevi merkezlerinden biri olan kutsal bir ziyaret mekanıdır. Hacı Bayram-ı Veli, Bayramiyye tarikatının kurucusu olup, şair, mutasavvıf ve halk ozanıdır. Türkçe şiirleriyle halkın gönlünde taht kuran Hacı Bayram, 'Çıkalım bağa kaçalım bağa, şu güzel havada seyreyleyelim' dizesiyle başlayan meşhur şiirle tanınır. Türbe, Hacı Bayram Camii'nin hemen bitişiğinde, Augustus Tapınağı kalıntılarının yanında yer almaktadır. Osmanlı mimari tarzında inşa edilen türbe, sade ancak etkileyici taş işçiliğiyle dikkat çeker. İçeride Hacı Bayram-ı Veli'nin sandukası bulunmakta ve üzeri yeşil örtüyle kaplıdır. Her yıl on binlerce mürit ve ziyaretçi, özellikle Ramazan ayı, Regaip Kandili ve dini bayramlarda türbeyi ziyaret ederek dua etmekte ve maneviyat aramaktadır. Türbe çevresinde tarihi türbeler, çeşmeler ve mezarlık alanları bulunmakta olup, Ankara'nın tarihi ve dini kimliğinin önemli bir parçasını oluşturmaktadır.",
		"resim": "images/place-10.svg",
		"images": ["images/place-10.svg"]
	},
	{
		"id": 11,
		"isim": "Ulucanlar Cezaevi Müzesi",
		"sehir": "Ankara",
		"kategori": "Müzeler",
		"lat": 39.9290,
		"lon": 32.8598,
		"kisa": "Tarihi cezaevi müzeye dönüştürülmüş.",
		"uzun": "Ulucanlar Cezaevi Müzesi, Ankara'nın Altındağ ilçesinde 1925 yılında açılan ve 2006 yılına kadar faaliyet gösteren, ardından 2011'de tamamen kapatılan ve 2011 yılından itibaren müzeye dönüştürülen Türkiye'nin siyasi tarihine tanıklık etmiş önemli bir yapıdır. Cumhuriyet döneminin en uzun süre hizmet veren cezaevlerinden biri olan Ulucanlar, özellikle siyasi mahkumların tutulduğu bir cezaevi olarak bilinmektedir. 1960'lı ve 1980'li yıllarda gerçekleşen askeri darbe dönemlerinde pek çok siyasi tutuklu bu cezaevinde hapis yatmıştır. Müzede orijinal hücreleri, koğuşları, ziyaret odaları, infaz odasını ve mahkum eşyalarını görmek mümkündür. Sergiler arasında ünlü mahkumların mektupları, fotoğrafları, kişisel eşyaları ve belgeleri yer almaktadır. Deniz Gezmiş, Yusuf Aslan, Hüseyin İnan gibi idam edilen siyasi mahkumların hikayeleri de müzede anlatılmaktadır. Müze, Türkiye'nin yakın siyasi tarihine dair toplumsal hafızanın korunması ve genç nesillere aktarılması açısından büyük önem taşımaktadır. Rehberli turlar ve eğitim programları ile ziyaretçilere derin bir tarih bilinci kazandırılmaktadır.",
		"resim": "images/place-11.svg",
		"images": ["images/place-11.svg"]
	},
	{
		"id": 12,
		"isim": "Seğmenler Parkı",
		"sehir": "Ankara",
		"kategori": "Parklar",
		"lat": 39.9110,
		"lon": 32.8400,
		"kisa": "Şehir içi yeşil alanlardan biri.",
		"uzun": "Seğmenler Parkı, Ankara'nın Yenimahalle ilçesinde yer alan, geniş yeşil alanları, yürüyüş ve koşu parkurları, bisiklet yolları ve rekreasyon tesisleriyle şehrin en sevilen parklarından biridir. Park, 1990'lı yıllarda modern kent parkı konseptiyle tasarlanmış ve zamanla Ankara halkının en çok tercih ettiği piknik ve spor alanlarından biri haline gelmiştir. Geniş çim alanları, ağaçlandırılmış bölgeleri, gölet ve su kanalları, botanik bahçeleri ve renkli çiçek tarhlarıyla dikkat çekmektedir. Parkta çocuklar için çeşitli oyun grupları, spor alanları, açık hava fitness ekipmanları ve basketbol-voleybol sahaları bulunmaktadır. Hafta sonları aileler piknik yapmak, gençler spor yapmak ve çocuklar oyun alanlarında vakit geçirmek için buraya gelmektedir. Parkta ayrıca açık hava konserleri, tiyatro gösterileri ve kültürel etkinliklerin düzenlendiği amfiteatr sahne de mevcuttur. Gölette kuş türleri yaşamakta ve doğa gözlemcileri için ilgi çekici bir alan oluşturmaktadır. Seğmenler Parkı, Ankara'nın modern yaşam tarzı ve yeşil alanlarla şehir planlaması konusundaki başarılı örneklerinden biridir.",
		"resim": "images/place-12.svg",
		"images": ["images/place-12.svg"]
	},
	{
		"id": 13,
		"isim": "Kurtuluş Savaşı Müzesi",
		"sehir": "İzmir",
		"kategori": "Müzeler",
		"lat": 38.4237,
		"lon": 27.1428,
		"kisa": "Kurtuluş Savaşı dönemiyle ilgili eserler.",
		"uzun": "Kurtuluş Savaşı Müzesi, İzmir'in Konak ilçesinde bulunan ve Türk Kurtuluş Savaşı'nın İzmir cephesindeki gelişmelerini, 9 Eylül 1922'de İzmir'in düşman işgalinden kurtuluşunu ve Milli Mücadele döneminin önemli olaylarını belgeleyen tarihi bir müzedir. Müze binası, 1933 yılında Atatürk'ün İzmir'i ziyareti sırasında kaldığı tarihi bir yapıdır ve 1988 yılında müzeye dönüştürülmüştür. Sergilerde Kurtuluş Savaşı'na ait belgeler, fotoğraflar, haritalar, gazete kupürleri, kişisel eşyalar, asker üniformaları, silahlar, madalyalar ve savaş dönemine ait çeşitli malzemeler bulunmaktadır. Özellikle İzmir'in işgali (15 Mayıs 1919) ve kurtuluşu (9 Eylül 1922) arasındaki üç yıllık dönemdeki olaylar, askeri stratejiler ve sivil hayattaki değişimler detaylı bir şekilde anlatılmaktadır. Müzede Mustafa Kemal Atatürk'ün İzmir'e girişi, İzmir İktisat Kongresi ve Ege bölgesindeki direniş hareketlerine dair önemli bilgiler yer almaktadır. Müze, Türk tarihinin en kritik dönemlerinden birine ışık tutarak genç nesillere milli bilinç kazandırmayı amaçlamaktadır.",
		"resim": "images/place-13.svg",
		"images": ["images/place-13.svg"]
	},
	{
		"id": 14,
		"isim": "Konak Meydanı",
		"sehir": "İzmir",
		"kategori": "Tarihi Semt",
		"lat": 38.4258,
		"lon": 27.1425,
		"kisa": "Tarihi İzmir'in merkezi, Saat Kulesi.",
		"uzun": "Konak Meydanı, İzmir'in kalbi ve sembolü olarak kabul edilen, Ege Denizi kıyısında yer alan tarihi ve sosyal açıdan son derece önemli bir meydandır. Meydanın en ünlü yapısı, 1901 yılında II. Abdülhamid döneminde Osmanlı İmparatorluğu'nun 25. kuruluş yıldönümü münasebetiyle inşa edilen İzmir Saat Kulesi'dir. 25 metre yüksekliğindeki bu zarif kule, dönemin Levanten mimarisinden etkilenen eklektik bir tarzda tasarlanmış olup, Alman İmparatoru II. Wilhelm tarafından hediye edilen saatlerle donatılmıştır. Saat Kulesi'nin dört cephesi de farklı motifler ve Osmanlı tuğralarıyla süslenmiştir. Meydanda ayrıca Yalı Camii (1755), Konak Pier alışveriş merkezi ve İzmir Valiliği binası gibi tarihi yapılar bulunmaktadır. Konak Meydanı, İzmir halkının ve turistlerin buluşma noktası olup, hafta sonları açılan pazarlar, kültürel etkinlikler ve mitingler için kullanılmaktadır. Meydan, İzmir'in modern ve tarihsel kimliğinin bir arada yaşadığı, deniz manzarası eşliğinde fotoğraf çekimi için ideal bir lokasyondur. Tramvay hattı, vapur iskelesi ve metro bağlantısıyla İzmir'in ulaşım merkezlerinden biridir.",
		"resim": "images/place-14.svg",
		"images": ["images/place-14.svg"]
	},
	{
		"id": 15,
		"isim": "Kemeraltı Çarşısı",
		"sehir": "İzmir",
		"kategori": "Tarihi Yerler",
		"lat": 38.4246,
		"lon": 27.1435,
		"kisa": "Osmanlı dönemine ait ticari merkez.",
		"uzun": "Kemeraltı Çarşısı, İzmir'in tarihi ticaret merkezi olarak 17. yüzyıldan beri faaliyet gösteren, dar sokakları, tarihi hanları, kervansarayları, camileri ve dükkânlarıyla Osmanlı döneminin canlı atmosferini günümüze taşıyan büyüleyici bir çarşıdır. Adını üzerindeki taş kemerlerden alan çarşı, kilometrelerce uzanan dar kaldırımlı yolları, renkli vitrinleri ve geleneksel Ege mimarisiyle dikkat çekmektedir. Kemeraltı'nda tekstil ürünleri, deri eşya, kuyumculuk, antika, kitap, baharat, baharat karışımları, yerel lezzetler ve el sanatları ürünleri satan yüzlerce dükkan bulunmaktadır. Çarşı içinde Hisar Camii, Şadırvan Camii, Kızlarağası Hanı ve tarihi sinagoglar gibi dini ve kültürel yapılar yer almaktadır. Kızlarağası Hanı, restore edilerek sanat atölyeleri, galeriler ve kafeler barındıran bir kültür merkezi haline getirilmiştir. Kemeraltı'nın otantik kahvehanelerinde Türk kahvesi içmek, midye dolma, kumru, gevrek ve boyoz gibi yerel lezzetleri tatmak İzmir deneyiminin vazgeçilmez parçalarıdır. Çarşı, hem alışveriş hem de tarihi doku keşfi için ideal bir yerdir ve her gün yerli halk ile turistlerin akınına uğramaktadır.",
		"resim": "images/place-15.svg",
		"images": ["images/place-15.svg"]
	},
	{
		"id": 16,
		"isim": "Alsancak Sahili",
		"sehir": "İzmir",
		"kategori": "Doğa",
		"lat": 38.4421,
		"lon": 27.1414,
		"kisa": "Deniz kıyısı ve modern sahil şeridi.",
		"uzun": "Alsancak Sahili, İzmir'in Kordon olarak da bilinen en popüler sahil şeridinde, Cumhuriyet Meydanı ile Gündoğdu Meydanı arasında uzanan, modern şehir yaşamının ve deniz kenarı rekreasyonunun mükemmel bir birleşimi olan canlı bir bölgedir. 19. yüzyılda Levanten ailelerin yerleşim bölgesi olarak gelişen Alsancak, günümüzde İzmir'in en kozmopolit ve modern semtlerinden biridir. Sahil boyunca uzanan geniş yürüyüş yolu (Kordon), palmiye ağaçları, heykeller, anıtlar, çiçek tarhları ve oturma alanlarıyla donatılmıştır. Deniz manzarası eşliğinde yürüyüş yapmak, koşmak veya bisiklet sürmek İzmir'in vazgeçilmez aktiviteleri arasındadır. Sahil boyunca dizilen kafe, restoran, balık lokantaları ve barlar, sabah kahvaltısından gece hayatına kadar her saatte canlılık sunar. Özellikle akşam saatlerinde batı güneşinin Ege Denizi'ni turuncu-kırmızı tonlarla boyadığı manzara izlemek büyüleyicidir. Alsancak Sahili, İzmir'in sosyal yaşamının merkezidir ve hafta sonları aileler, gençler ve turistlerle doludur. Bölgede ayrıca kültür merkezleri, konser alanları ve sanat galerileri de bulunmaktadır. İzmir'in modern, dinamik ve denizle iç içe yaşam tarzını deneyimlemek için mutlaka görülmesi gereken bir yerdir.",
		"resim": "images/place-16.svg",
		"images": ["images/place-16.svg"]
	},
	{
		"id": 17,
		"isim": "Bergama Antik Kenti",
		"sehir": "İzmir",
		"kategori": "Arkeolojik Alanlar",
		"lat": 39.1255,
		"lon": 27.1807,
		"kisa": "Antik dünyanın önemli şehirlerinden biri.",
		"uzun": "Bergama Antik Kenti, İzmir'in Bergama ilçesinde bulunan ve Helenistik dönemin en önemli kültür, sanat ve bilim merkezlerinden biri olan UNESCO Dünya Mirası Listesi'nde yer alan muhteşem bir arkeolojik alandır. M.Ö. 3. yüzyılda Pergamon Krallığı'nın başkenti olan şehir, dönemin en büyük kütüphanesine (200.000 ciltlik eser), en gelişmiş tıp merkezine (Asklepion) ve en etkileyici tiyatrosuna sahipti. Akropol tepesinde yer alan Bergama Tiyatrosu, 10.000 kişilik kapasitesi ve dik yamaçtaki konumuyla antik dünyanın en etkileyici tiyatrolarından biridir. Asklepion, antik dönemin en ünlü şifa merkeziydi ve burada Galenos gibi ünlü hekimler çalışmıştır. Tedavi yöntemleri arasında su terapisi, çamur banyoları, psikoterapi ve tiyatro gösterileri bulunmaktaydı. Bergama'da pergamen (양피지) adı verilen hayvan derisinden yapılan yazı malzemesi icat edilmiştir. Kızıl Avlu (Serapis Tapınağı), Roma döneminden kalma devasa bir tapınak yapısıdır. Bergama Müzesi'nde bölgede yapılan kazılardan çıkarılan heykeller, mozaikler, sikke ve günlük eşyalar sergilenmektedir. Bergama, tarihi zenginliği, mimari harikası yapıları ve kültürel önemiyle her yıl binlerce arkeoloji ve tarih meraklısını cezbetmektedir.",
		"resim": "images/place-17.svg",
		"images": ["images/place-17.svg"]
	},
	{
		"id": 18,
		"isim": "Efes Antik Kenti",
		"sehir": "İzmir",
		"kategori": "Arkeolojik Alanlar",
		"lat": 37.9449,
		"lon": 27.3776,
		"kisa": "Yedi Harika'dan Artemis Tapınağı.",
		"uzun": "Efes Antik Kenti, İzmir'in Selçuk ilçesinde bulunan ve antik dünyanın en büyük, en zengin ve en iyi korunmuş şehirlerinden biri olan, UNESCO Dünya Mirası Listesi'nde yer alan olağanüstü bir arkeolojik alandır. M.Ö. 10. yüzyılda İyon kolonistleri tarafından kurulan Efes, Roma İmparatorluğu döneminde Anadolu'nun başkenti ve 250.000 nüfuslu bir metropol haline gelmiştir. Şehrin en ünlü yapısı, Antik Dünyanın Yedi Harikası'ndan biri olan Artemis Tapınağı'dır (günümüzde sadece bir sütunu ayakta kalmıştır). Celsus Kütüphanesi, iki katlı muhteşem cephesi ve 12.000 kitaplık koleksiyonuyla Roma döneminin en önemli kütüphanelerinden biriydi. Efes Tiyatrosu, 24.000 kişilik kapasitesiyle dünyanın en büyük antik tiyatrolarından biridir ve halen konserler için kullanılmaktadır. Mermer yol boyunca sıralanan sütunlu caddeler, agoralar, hamamlar, Zeus Tapınağı ve zengin evlerin mozaikleri Efes'in ihtişamını gözler önüne sermektedir. Terrace House (Yamaç Evleri), zengin Romalıların yaşadığı lüks evlerdir ve freskler, mozaikler ve ısıtma sistemleriyle dönemin yaşam standardını göstermektedir. Efes, her yıl 2 milyondan fazla turist tarafından ziyaret edilmektedir.",
		"resim": "images/place-18.svg",
		"images": ["images/place-18.svg"]
	},
	{
		"id": 19,
		"isim": "Meryem Ana Evi",
		"sehir": "İzmir",
		"kategori": "Dini/Dindar",
		"lat": 37.8970,
		"lon": 27.3288,
		"kisa": "Meryem Ana'nın yaşadığı yer.",
		"uzun": "Meryem Ana Evi, İzmir'in Selçuk ilçesinde, Efes Antik Kenti'nin yakınlarında Bülbül Dağı'nın (Aladag) yamaçlarında yer alan ve Hristiyanlık tarihinin en kutsal mekanlarından biri olarak kabul edilen dini bir ziyaret yeridir. İnanışa göre, İsa Mesih'in çarmıha gerilmesinden sonra Havari Yohanna, Meryem Ana'yı Kudüs'ten Efes'e getirmiş ve Meryem yaşamının son yıllarını bu evde geçirerek burada vefat etmiştir. 19. yüzyılda Alman rahibesi Anne Catherine Emmerich'in vizyonları sonucunda evin konumu tespit edilmiş ve 1891 yılında keşfedilmiştir. Arkeolojik araştırmalar, evin temellerinin 1. yüzyıla ait olduğunu doğrulamıştır. 1896 yılında Vatikan tarafından resmi olarak tanınan ev, 1967'de Papa VI. Paul, 1979'da Papa II. Jean Paul ve 2006'da Papa XVI. Benedict tarafından ziyaret edilmiştir. Bu papalar, evi bir hac yeri olarak ilan etmişlerdir. Ev, küçük ve mütevazı bir taş yapıdır ve içinde Meryem Ana'nın heykeli ve dua alanları bulunmaktadır. Dışarıda ise dilek duvarı, dilek ağacı ve Meryem Ana'nın kutsandığı kabul edilen su kaynağı bulunmaktadır. Her yıl yüzbinlerce Hristiyan, özellikle 15 Ağustos'ta kutlanan Meryem Ana Yortusu'nda buraya gelmektedir.",
		"resim": "images/place-19.svg",
		"images": ["images/place-19.svg"]
	},
	{
		"id": 20,
		"isim": "Topkapı Sarayı",
		"sehir": "İstanbul",
		"kategori": "Tarihi Yapılar",
		"lat": 41.0186,
		"lon": 28.9838,
		"kisa": "Osmanlı padişahlarının ikamet ettiği saray.",
		"uzun": "Topkapı Sarayı, 15-19. yüzyıllarda Osmanlı İmparatorluğu'nun yönetim merkezi olan ve padişahların ikamet ettiği muazzam bir saraydır. 700 bin metrekarelik alanı üzerinde inşa edilen saray, harem, selamlık, hazine dairesi ve cami gibi birçok bölümü içerir. Günümüzde müze olarak hizmet veren Topkapı Sarayı, Osmanlı mimarisi ve sanat eserlerinin en geniş koleksiyonlarını sunmaktadır.",
		"resim": "images/place-20.svg",
		"images": ["images/place-20.svg"]
	},
	{
		"id": 21,
		"isim": "Aspendos Tiyatrosu",
		"sehir": "Antalya",
		"kategori": "Arkeolojik Alanlar",
		"lat": 36.9096,
		"lon": 31.1776,
		"kisa": "İyi korunmuş antik tiyatro.",
		"uzun": "Aspendos Tiyatrosu, Roma döneminden kalma olağanüstü korunmuş mimarisi ve üstün akustiği ile bilinir. Günümüzde yaz aylarında uluslararası opera ve bale festivallerine ev sahipliği yapan bir alan olarak kullanılır.",
		"resim": "images/place-21.svg",
		"images": ["images/place-21.svg"]
	},
	{
		"id": 22,
		"isim": "Perge Antik Kenti",
		"sehir": "Antalya",
		"kategori": "Arkeolojik Alanlar",
		"lat": 36.8939,
		"lon": 30.9470,
		"kisa": "Agora ve stadyum kalıntıları.",
		"uzun": "Perge Antik Kenti, geniş sütunlu caddeleri, stadyumu ve agora kalıntılarıyla Helenistik dönem kent planlamasını gösterir.",
		"resim": "images/place-22.svg",
		"images": ["images/place-22.svg"]
	},
	{
		"id": 23,
		"isim": "Safranbolu Evleri",
		"sehir": "Karabük",
		"kategori": "Tarihi Semt",
		"lat": 41.2596,
		"lon": 32.6679,
		"kisa": "Osmanlı dönemi konaklarıyla ünlü kasaba.",
		"uzun": "Safranbolu, Osmanlı dönemine ait iyi korunmuş ahşap ve taş konakları, dar sokakları ve geleneksel şehir dokusuyla tanınır.",
		"resim": "images/place-23.svg",
		"images": ["images/place-23.svg"]
	},
	{
		"id": 24,
		"isim": "Amasya Kral Kaya Mezarları",
		"sehir": "Amasya",
		"kategori": "Arkeolojik Alanlar",
		"lat": 40.6529,
		"lon": 35.8288,
		"kisa": "Kaya mezarları ve tarihî şehir manzarası.",
		"uzun": "Amasya'daki kral kaya mezarları, antik krallara ait anıt mezarları kaya yüzeyine oyma tekniğiyle şekillendirilmiş olarak gösterir.",
		"resim": "images/place-24.svg",
		"images": ["images/place-24.svg"]
	},
	{
		"id": 25,
		"isim": "Troy Antik Kenti",
		"sehir": "Çanakkale",
		"kategori": "Arkeolojik Alanlar",
		"lat": 39.9578,
		"lon": 26.2385,
		"kisa": "Truva Atı efsanesiyle ünlü antik kent.",
		"uzun": "Truva (Troy) Antik Kenti, Homeros'un destanlarında adı geçen kent olarak mitoloji ve arkeolojinin buluştuğu yerdir.",
		"resim": "images/place-25.svg",
		"images": ["images/place-25.svg"]
	},
	{
		"id": 26,
		"isim": "Sumela Manastırı",
		"sehir": "Trabzon",
		"kategori": "Dini/Dindar",
		"lat": 40.6760,
		"lon": 39.7483,
		"kisa": "Uçurum üzerindeki tarihi manastır.",
		"uzun": "Sumela Manastırı, dik bir kayalık yüzeye inşa edilmiş olmasıyla dikkat çeker ve içindeki freskler ile Ortodoks manastır geleneğinin izlerini taşır.",
		"resim": "images/place-26.svg",
		"images": ["images/place-26.svg"]
	},
	{
		"id": 27,
		"isim": "Göbekli Tepe",
		"sehir": "Şanlıurfa",
		"kategori": "Arkeolojik Alanlar",
		"lat": 37.2236,
		"lon": 38.9226,
		"kisa": "Dünyanın bilinen en eski tapınak komplekslerinden biri.",
		"uzun": "Göbekli Tepe, Neolitik döneme ait, insanlık tarihinin bilinen en erken anıtsal tapınak kompleksi olarak kabul edilir.",
		"resim": "images/place-27.svg",
		"images": ["images/place-27.svg"]
	},
	{
		"id": 28,
		"isim": "İshak Paşa Sarayı",
		"sehir": "Ağrı",
		"kategori": "Tarihi Yapılar",
		"lat": 39.6933,
		"lon": 44.1667,
		"kisa": "İhtişamlı bir saray-kompleks.",
		"uzun": "İshak Paşa Sarayı, saray, cami, hamam ve yönetim bölümlerini içeren geniş bir kompleks olup, Doğu Anadolu'nun mimari zenginliğini yansıtır.",
		"resim": "images/place-28.svg",
		"images": ["images/place-28.svg"]
	},
	{
		"id": 29,
		"isim": "Mardin Taş Evleri",
		"sehir": "Mardin",
		"kategori": "Tarihi Semt",
		"lat": 37.3167,
		"lon": 40.7433,
		"kisa": "Taş mimarisi ve dar sokaklarıyla ünlü şehir.",
		"uzun": "Mardin, taş evleri, tarihî çarşıları ve manzarasıyla ziyaretçi çeker.",
		"resim": "images/place-29.jpg",
		"images": ["images/place-29.jpg"]
	},
	{
		"id": 30,
		"isim": "Kapadokya",
		"sehir": "Nevşehir",
		"kategori": "Doğa/Jeolojik",
		"lat": 38.6426,
		"lon": 34.8276,
		"kisa": "Peri bacaları ve kaya içi yerleşimler.",
		"uzun": "Kapadokya, rüzgar ve su erozyonuyla şekillenmiş peri bacaları, yer altı şehirleri ve kaya oyma kiliseleriyle benzersiz bir coğrafi ve kültürel mirastır.",
		"resim": "images/place-30.jpg",
		"images": ["images/place-30.jpg"]
	},
	{
		"id": 31,
		"isim": "Nemrut Dağı",
		"sehir": "Adıyaman",
		"kategori": "Arkeolojik Alanlar",
		"lat": 37.9847,
		"lon": 38.7402,
		"kisa": "Dev heykeller ve tümülüs.",
		"uzun": "Nemrut Dağı, Kommagene krallığının anıtsal tümülüs ve dev heykelleri ile ünlüdür; özellikle gün doğumu ve gün batımındaki panoramik manzarası ziyaretçileri çeker.",
		"resim": "images/place-31.jpg",
		"images": ["images/place-31.jpg"]
	},
	{
		"id": 32,
		"isim": "Kaş Dalış Bölgeleri",
		"sehir": "Antalya",
		"kategori": "Doğa/Su Sporları",
		"lat": 36.1968,
		"lon": 29.9845,
		"kisa": "Dalış ve mavi tur için popüler bir liman kasabası.",
		"uzun": "Kaş, berrak denizi ve batıklarıyla dalış meraklıları için önemli bir merkezdir.",
		"resim": "images/place-32.jpg",
		"images": ["images/place-32.jpg"]
	},
	{
		"id": 33,
		"isim": "Bodrum Kalesi",
		"sehir": "Muğla",
		"kategori": "Tarihi Yapılar",
		"lat": 37.0379,
		"lon": 27.4305,
		"kisa": "Güzel bir deniz manzarasına sahip ortaçağ kalesi.",
		"uzun": "Bodrum Kalesi, deniz kenarındaki konumu ve içinde bulunan müze ile ziyaretçilerin ilgisini çeker.",
		"resim": "images/place-33.jpg",
		"images": ["images/place-33.jpg"]
	},
	{
		"id": 34,
		"isim": "Bursa Ulu Camii",
		"sehir": "Bursa",
		"kategori": "Dini/Dindar",
		"lat": 40.1868,
		"lon": 29.0610,
		"kisa": "Osmanlı dini mimarisinin önemli örneklerinden.",
		"uzun": "Ulu Camii, Osmanlı dönemi dini mimarisinin önemli örneklerinden biridir.",
		"resim": "images/place-34.jpg",
		"images": ["images/place-34.jpg"]
	},
	{
		"id": 35,
		"isim": "Fethiye Ölüdeniz",
		"sehir": "Muğla",
		"kategori": "Doğa/Plaj",
		"lat": 36.5489,
		"lon": 29.1196,
		"kisa": "Dünyaca ünlü mavi lagün.",
		"uzun": "Ölüdeniz, sakin turkuaz suları ve lagün yapısıyla deniz ve doğa tutkunları için ideal bir destinasyondur.",
		"resim": "images/place-35.svg",
		"images": ["images/place-35.svg"]
	},
	{
		"id": 36,
		"isim": "Diyarbakır Surları",
		"sehir": "Diyarbakır",
		"kategori": "Tarihi Yapılar",
		"lat": 37.9101,
		"lon": 40.2433,
		"kisa": "Tarihi şehir surları ve Hevsel Bahçeleri.",
		"uzun": "Diyarbakır Surları, taş işçiliği ve uzunluğu ile bilinen, kentin tarihsel belleğini taşıyan geniş bir savunma sistemidir.",
		"resim": "images/place-36.svg",
		"images": ["images/place-36.svg"]
	},
	{
		"id": 37,
		"isim": "Ankara Kalesi",
		"sehir": "Ankara",
		"kategori": "Tarihi Yapılar",
		"lat": 39.9341,
		"lon": 32.8597,
		"kisa": "Şehrin ortaçağ kalesi ve çevresi.",
		"uzun": "Ankara Kalesi, Roma, Bizans ve Selçuklu dönemlerine ait izler taşıyan, şehrin tarihi merkezinde yer alan bir yapıdır.",
		"resim": "images/place-37.svg",
		"images": ["images/place-37.svg"]
	},
	{
		"id": 38,
		"isim": "Anadolu Medeniyetleri Müzesi",
		"sehir": "Ankara",
		"kategori": "Müzeler",
		"lat": 39.9250,
		"lon": 32.8543,
		"kisa": "Zengin Anadolu tarihine ait eserler sergilenir.",
		"uzun": "Anadolu Medeniyetleri Müzesi, Anadolu topraklarında ortaya çıkmış medeniyetlerin binlerce yıllık eserlerini kronolojik düzende sergiler.",
		"resim": "images/place-38.svg",
		"images": ["images/place-38.svg"]
	},
	{
		"id": 39,
		"isim": "Hamamönü",
		"sehir": "Ankara",
		"kategori": "Tarihi Semt",
		"lat": 39.9305,
		"lon": 32.8629,
		"kisa": "Restore edilmiş Osmanlı mahallesi ve el sanatları bölgesi.",
		"uzun": "Hamamönü, restore edilmiş Osmanlı dönemi konakları, taş döşeli dar sokakları ve geleneksel atölyeleriyle bilinir.",
		"resim": "images/place-39.svg",
		"images": ["images/place-39.svg"]
	},
	{
		"id": 40,
		"isim": "Etnografya Müzesi",
		"sehir": "Ankara",
		"kategori": "Müzeler",
		"lat": 39.9257,
		"lon": 32.8502,
		"kisa": "Türk etnografyasına ait eserler sergilenir.",
		"uzun": "Etnografya Müzesi, Türk kültürüne ait günlük yaşam objeleri, geleneksel giysiler, silahlar ve tören eşyalarını sergiler.",
		"resim": "images/place-40.svg",
		"images": ["images/place-40.svg"]
	},
	{
		"id": 41,
		"isim": "Atatürk Orman Çiftliği",
		"sehir": "Ankara",
		"kategori": "Doğa",
		"lat": 39.9243,
		"lon": 32.7986,
		"kisa": "Geniş park ve tarım alanları, seralar.",
		"uzun": "Atatürk Orman Çiftliği, hem şehir içinde geniş yeşil alan sağlayan bir rekreasyon bölgesi hem de eğitim amaçlı tarım ve hayvancılık uygulamalarına ev sahipliği yapan bir çiftliktir.",
		"resim": "images/place-41.svg",
		"images": ["images/place-41.svg"]
	},
	{
		"id": 42,
		"isim": "Gençlik Parkı",
		"sehir": "Ankara",
		"kategori": "Parklar",
		"lat": 39.9261,
		"lon": 32.8590,
		"kisa": "Şehir merkezindeki büyük park ve gölet.",
		"uzun": "Gençlik Parkı, Ankara'nın merkezinde geniş yürüyüş yolları, oyun alanları ve büyük bir gölete sahip olan popüler bir rekreasyon alanıdır.",
		"resim": "images/place-42.svg",
		"images": ["images/place-42.svg"]
	},
	{
		"id": 43,
		"isim": "Ayasofya",
		"sehir": "İstanbul",
		"kategori": "Tarihi Yapılar",
		"lat": 41.0086,
		"lon": 28.9802,
		"kisa": "Tarihi kilise, cami ve müze olarak bilinir.",
		"uzun": "Ayasofya, Bizans döneminde inşa edilen ve daha sonra Osmanlı döneminde cami olarak kullanılan, mimari açıdan dünyanın en önemli anıtlarından biridir.",
		"resim": "images/place-43.svg",
		"images": ["images/place-43.svg"]
	},
	{
		"id": 44,
		"isim": "Sultanahmet Camii",
		"sehir": "İstanbul",
		"kategori": "Dini/Dindar",
		"lat": 41.0055,
		"lon": 28.9768,
		"kisa": "Mavi Camii olarak da bilinir.",
		"uzun": "Sultanahmet Camii (Mavi Camii), iç mekanındaki mavi çinilerle süslü duvarları ve geniş avlusuyla tanınır.",
		"resim": "images/place-44.svg",
		"images": ["images/place-44.svg"]
	},
	{
		"id": 45,
		"isim": "Konak Meydanı",
		"sehir": "İzmir",
		"kategori": "Tarihi Semt",
		"lat": 38.4192,
		"lon": 27.1287,
		"kisa": "İzmir'in merkezi ve simge meydanı.",
		"uzun": "Konak Meydanı, İzmir'in sosyo-kültürel yaşamının kalbidir; saat kulesi, belediye binası ve deniz manzarasıyla fotoğraflık bir mekandır.",
		"resim": "images/place-45.svg",
		"images": ["images/place-45.svg"]
	},
	{
		"id": 46,
		"isim": "Çatalhöyük",
		"sehir": "Konya",
		"kategori": "Arkeolojik Alanlar",
		"lat": 37.1440,
		"lon": 33.0420,
		"kisa": "Neolitik döneme ait önemli yerleşim.",
		"uzun": "Çatalhöyük, erken yerleşimlerin izlerini taşıyan arkeolojik bir bölgedir.",
		"resim": "images/place-46.jpg",
		"images": ["images/place-46.jpg"]
	},
	{
		"id": 47,
		"isim": "Kızkalesi",
		"sehir": "Mersin",
		"kategori": "Tarihi Yapılar/Plaj",
		"lat": 36.5094,
		"lon": 34.1031,
		"kisa": "Denizde yer alan kale kalıntısı.",
		"uzun": "Kızkalesi, denizin ortasında yer alan tarihi bir kale harabesi ve kıyı şeridinde güzel plaj alanlarıyla turistlerin ilgisini çeker.",
		"resim": "images/place-47.svg",
		"images": ["images/place-47.svg"]
	},
	{
		"id": 48,
		"isim": "Amasra",
		"sehir": "Bartın",
		"kategori": "Tarihi Semt/Plaj",
		"lat": 41.7376,
		"lon": 32.3872,
		"kisa": "Tarihi liman kenti ve plajları.",
		"uzun": "Amasra, Karadeniz kıyısında yer alan tarihî liman kenti olup, ahşap evleri, küçük koyları ve deniz manzarasıyla ünlüdür.",
		"resim": "images/place-48.svg",
		"images": ["images/place-48.svg"]
	},
	{
		"id": 49,
		"isim": "Beypazarı Tarihi Evleri",
		"sehir": "Ankara",
		"kategori": "Tarihi Semt",
		"lat": 40.1779,
		"lon": 31.6619,
		"kisa": "Türk ev mimarisinin güzel örnekleri.",
		"uzun": "Beypazarı'nın taş ve ahşap karışımı tarihi evleri, geleneksel el sanatları, yöresel lezzetler ve nostaljik atmosferi ile ünlüdür.",
		"resim": "images/place-49.svg",
		"images": ["images/place-49.svg"]
	},
	{
		"id": 50,
		"isim": "Pamukkale",
		"sehir": "Denizli",
		"kategori": "Doğa/Termal",
		"lat": 37.9204,
		"lon": 29.1210,
		"kisa": "Beyaz travertenler ve termal havuzlar.",
		"uzun": "Pamukkale, kalsiyum karbonat açısından zengin sıcak sulardan oluşan beyaz travertenler ve antik Hierapolis harabeleriyle ünlüdür.",
		"resim": "images/place-50.svg",
		"images": ["images/place-50.svg"]
	},
	{
		"id": 51,
		"isim": "Alaçatı",
		"sehir": "İzmir",
		"kategori": "Tatil Beldesi",
		"lat": 38.3270,
		"lon": 26.3912,
		"kisa": "Rüzgâr sörfü merkezi ve taş evler.",
		"uzun": "Alaçatı, rüzgâr sörfü sporları, butik otelleri, taş evleri ve dar sokakları ile popüler bir tatil beldesidir.",
		"resim": "images/place-51.svg",
		"images": ["images/place-51.svg"]
	},
	{
		"id": 52,
		"isim": "Ölüdeniz Yamaç Paraşütü",
		"sehir": "Muğla",
		"kategori": "Doğa/Macera",
		"lat": 36.5489,
		"lon": 29.1196,
		"kisa": "Dünyaca ünlü yamaç paraşütü noktası.",
		"uzun": "Ölüdeniz, hem mavi lagünü hem de Babadağ'dan yapılan yamaç paraşütü uçuşlarıyla ünlüdür.",
		"resim": "images/place-52.svg",
		"images": ["images/place-52.svg"]
	},
	{
		"id": 53,
		"isim": "Hasankeyf",
		"sehir": "Batman",
		"kategori": "Arkeolojik Alanlar",
		"lat": 37.7167,
		"lon": 41.4167,
		"kisa": "Tarihi köprü ve kaya yerleşimleri.",
		"uzun": "Hasankeyf, Dicle Nehri üzerinde binlerce yıllık tarihi olan, kaya oyma evleri ve antik yapılarıyla dikkat çeker.",
		"resim": "images/place-53.svg",
		"images": ["images/place-53.svg"]
	},
	{
		"id": 54,
		"isim": "Ani Harabeleri",
		"sehir": "Kars",
		"kategori": "Arkeolojik Alanlar",
		"lat": 40.5069,
		"lon": 43.5722,
		"kisa": "Ortaçağ Ermeni başkenti kalıntıları.",
		"uzun": "Ani, İpek Yolu üzerinde yer alan ve ortaçağda önemli bir ticaret merkezi olan tarihi şehrin kalıntılarını barındırır.",
		"resim": "images/place-54.svg",
		"images": ["images/place-54.svg"]
	},
	{
		"id": 55,
		"isim": "Çıralı Plajı",
		"sehir": "Antalya",
		"kategori": "Doğa/Plaj",
		"lat": 36.3986,
		"lon": 30.4761,
		"kisa": "Caretta caretta kaplumbağaları ve sakin plaj.",
		"uzun": "Çıralı, caretta caretta kaplumbağalarının üreme alanı olan korunan bir plajdır.",
		"resim": "images/place-55.svg",
		"images": ["images/place-55.svg"]
	},
	{
		"id": 56,
		"isim": "Patara Antik Kenti",
		"sehir": "Antalya",
		"kategori": "Arkeolojik Alanlar",
		"lat": 36.2670,
		"lon": 29.3150,
		"kisa": "Antik liman kenti ve uzun kumsal.",
		"uzun": "Patara, Likya medeniyetinin önemli liman kentlerinden biri olup, 18 km uzunluğundaki kumsalıyla da ünlüdür.",
		"resim": "images/place-56.svg",
		"images": ["images/place-56.svg"]
	},
	{
		"id": 57,
		"isim": "Olympos Antik Kenti",
		"sehir": "Antalya",
		"kategori": "Arkeolojik Alanlar",
		"lat": 36.3989,
		"lon": 30.4708,
		"kisa": "Ormanlık alandaki antik kent kalıntıları.",
		"uzun": "Olympos, orman içinde yer alan bir antik kenttir ve yakınındaki Yanartaş (Chimaera) ile ünlüdür.",
		"resim": "images/place-57.svg",
		"images": ["images/place-57.svg"]
	},
	{
		"id": 58,
		"isim": "Karain Mağarası",
		"sehir": "Antalya",
		"kategori": "Arkeolojik Alanlar",
		"lat": 36.9667,
		"lon": 30.5500,
		"kisa": "Paleolitik dönem yerleşim mağarası.",
		"uzun": "Karain Mağarası, Türkiye'de sürekli yerleşim gören en eski mağaralardan biridir.",
		"resim": "images/place-58.svg",
		"images": ["images/place-58.svg"]
	},
	{
		"id": 59,
		"isim": "Ulucanlar Cezaevi Müzesi",
		"sehir": "Ankara",
		"kategori": "Müzeler",
		"lat": 39.9290,
		"lon": 32.8598,
		"kisa": "Tarihi cezaevi müzeye dönüştürülmüş.",
		"uzun": "Ulucanlar Cezaevi Müzesi, 20. yüzyıl Türkiye'sinin önemli siyasi tarihine dair izler barındırır.",
		"resim": "images/place-59.svg",
		"images": ["images/place-59.svg"]
	},
	{
		"id": 60,
		"isim": "Galata Kulesi",
		"sehir": "İstanbul",
		"kategori": "Tarihi Yapılar",
		"lat": 41.0256,
		"lon": 28.9744,
		"kisa": "Ortaçağ Ceneviz kulesi ve panoramik manzara.",
		"uzun": "Galata Kulesi, İstanbul'un simgelerinden biri olup, şehrin panoramik manzarasını sunar.",
		"resim": "images/place-60.svg",
		"images": ["images/place-60.svg"]
	},
	{
		"id": 61,
		"isim": "Dolmabahçe Sarayı",
		"sehir": "İstanbul",
		"kategori": "Tarihi Yapılar",
		"lat": 41.0391,
		"lon": 29.0001,
		"kisa": "Osmanlı'nın son dönem sarayı.",
		"uzun": "Dolmabahçe Sarayı, Osmanlı İmparatorluğu'nun son döneminde padişahların ikamet ettiği görkemli saraydır.",
		"resim": "images/place-61.svg",
		"images": ["images/place-61.svg"]
	},
	{
		"id": 62,
		"isim": "Yerebatan Sarnıcı",
		"sehir": "İstanbul",
		"kategori": "Tarihi Yapılar",
		"lat": 41.0084,
		"lon": 28.9778,
		"kisa": "Bizans dönemi yeraltı su deposu.",
		"uzun": "Yerebatan Sarnıcı, Bizans döneminde inşa edilen devasa bir yeraltı su deposudur.",
		"resim": "images/place-62.svg",
		"images": ["images/place-62.svg"]
	},
	{
		"id": 63,
		"isim": "Çanakkale Şehitler Abidesi",
		"sehir": "Çanakkale",
		"kategori": "Anıtlar",
		"lat": 40.0714,
		"lon": 26.2144,
		"kisa": "Çanakkale şehitleri anısına dikilen anıt.",
		"uzun": "Çanakkale Şehitler Abidesi, Çanakkale Savaşı'nda şehit düşenlerin anısına dikilmiş anıttır.",
		"resim": "images/place-63.svg",
		"images": ["images/place-63.svg"]
	},
	{
		"id": 64,
		"isim": "Assos Antik Kenti",
		"sehir": "Çanakkale",
		"kategori": "Arkeolojik Alanlar",
		"lat": 39.4908,
		"lon": 26.3389,
		"kisa": "Deniz manzaralı antik kent.",
		"uzun": "Assos, Aristoteles'in bir dönem yaşadığı antik kenttir ve Athena tapınağı kalıntılarıyla ünlüdür.",
		"resim": "images/place-64.svg",
		"images": ["images/place-64.svg"]
	},
	{
		"id": 65,
		"isim": "Kuşadası",
		"sehir": "Aydın",
		"kategori": "Tatil Beldesi",
		"lat": 37.8607,
		"lon": 27.2615,
		"kisa": "Popüler tatil ve kruvaziyer limanı.",
		"uzun": "Kuşadası, plajları, gece hayatı ve Efes'e yakınlığıyla popüler bir tatil beldesidir.",
		"resim": "images/place-65.svg",
		"images": ["images/place-65.svg"]
	},
	{
		"id": 66,
		"isim": "Alaçatı Değirmenleri",
		"sehir": "İzmir",
		"kategori": "Tarihi Yapılar",
		"lat": 38.3258,
		"lon": 26.3892,
		"kisa": "Tarihi taş yel değirmenleri.",
		"uzun": "Alaçatı'nın simgesi olan taş yel değirmenleri, kasabanın tepe noktasında yer alır.",
		"resim": "images/place-66.svg",
		"images": ["images/place-66.svg"]
	},
	{
		"id": 67,
		"isim": "Kelebekler Vadisi",
		"sehir": "Muğla",
		"kategori": "Doğa",
		"lat": 36.5500,
		"lon": 29.1083,
		"kisa": "Kelebek türlerinin yaşam alanı.",
		"uzun": "Kelebekler Vadisi, nadir kelebek türlerinin yaşadığı korunan bir doğa alanıdır.",
		"resim": "images/place-67.svg",
		"images": ["images/place-67.svg"]
	},
	{
		"id": 68,
		"isim": "Saklikent Kanyonu",
		"sehir": "Muğla",
		"kategori": "Doğa",
		"lat": 36.4667,
		"lon": 29.5167,
		"kisa": "Türkiye'nin en derin kanyonlarından.",
		"uzun": "Saklıkent Kanyonu, 18 km uzunluğunda ve 300 metre derinliğinde doğal bir oluşumdur.",
		"resim": "images/place-68.svg",
		"images": ["images/place-68.svg"]
	},
	{
		"id": 69,
		"isim": "Sümela Yolu",
		"sehir": "Trabzon",
		"kategori": "Doğa/Yürüyüş",
		"lat": 40.6850,
		"lon": 39.7450,
		"kisa": "Doğa yürüyüşü ve manzara rotası.",
		"uzun": "Sümela Manastırı'na ulaşan doğa yolu, yeşil ormanlar ve şelalelerle çevrilidir.",
		"resim": "images/place-69.svg",
		"images": ["images/place-69.svg"]
	},
	{
		"id": 70,
		"isim": "Uzungöl",
		"sehir": "Trabzon",
		"kategori": "Doğa",
		"lat": 40.6167,
		"lon": 40.3000,
		"kisa": "Yaylalarda doğal göl ve yeşil manzara.",
		"uzun": "Uzungöl, Karadeniz'in yeşil yaylalarında yer alan doğal bir göldür ve çay bahçeleriyle çevrilidir.",
		"resim": "images/place-70.svg",
		"images": ["images/place-70.svg"]
	}
]

